CorporatePortal.Core/CorporatePortal/Controllers/ChartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CorporatePortal.Controllers
{
    /// <summary>
    /// Контроллер для работы с диаграммой
    /// </summary>
    public class ChartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CorporatePortal.Core/CorporatePortal/Controllers/CorporateCultureController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CorporatePortal.Controllers
{
    /// <summary>
    /// Контроллер для работы с корпоративной культурой
    /// </summary>
    public class CorporateCultureController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CorporatePortal.Core/CorporatePortal/Controllers/NormativeDocumentsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CorporatePortal.Controllers
{
    /// <summary>
    /// Контроллер для работы с нормативными документами
    /// </summary>
    public class NormativeDocumentsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CorporatePortal.Core/CorporatePortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject RoleManager<IdentityRole> RoleManager

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Корпоративный портал</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/jquery-ui/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">РОСАТОМ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CorporateCulture" asp-action="Index">Корпоративная культура</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="NormativeDocuments" asp-action="Index">Нормативные документы</a>
                            </li>
                            if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Mentoring" asp-action="Index">Наставничество</a>
                                </li>
                            }
                            if (User.IsInRole("employee"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Задачи</a>
                                </li>
                            }
                            if (User.IsInRole("operator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Mark" asp-action="Index">Оценка</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Chart" asp-action="Index">Рейтинг</a>
                            </li>
                            if (!User.IsInRole("operator"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Mark" asp-action="MarkList">Оценка</a>
                            </li>
                            }                            
                            <li>
                                <a class="btn btn-secondary" style="margin-bottom:5px" onclick="PopupForm('@Url.Action("Index","Chat")')"> Бот</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            <a> &copy; 2021 - Копроративный портал РОСАТОМ</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/jquery/notify.min.js"></script>
    <script>
        //Форма открывается при нажатии кнопки "Добавить" или "Изменить"
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Бот',
                        height: 400,
                        width: 300,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }
                    });
                });
        }
    </script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>